#!/bin/bash


# From here: https://blog.testdouble.com/posts/2016-11-18-reconciling-tmux-and-ssh-agent-forwarding/
# Fix SSH auth socket location so agent forwarding works with tmux
if test "$SSH_AUTH_SOCK" ; then
    ln -sf $SSH_AUTH_SOCK ~/.ssh/ssh_auth_sock
fi

# https://superuser.com/questions/492289/x11-connection-uses-different-authentication-protocol-when-using-ssh-x#1189292
if read proto cookie && [ -n "$DISPLAY" ]; then
    if [ `echo $DISPLAY | cut -c1-10` = 'localhost:' ]; then
         # X11UseLocalhost=yes
         echo add unix:`echo $DISPLAY |
             cut -c11-` $proto $cookie
    else
         # X11UseLocalhost=no
         echo add $DISPLAY $proto $cookie
    fi | xauth -q -
fi

