ARRANGE: ROW
ALIGN: TOP
ORDER:
  - DP-2
  - eDP-1
AUTO_SCALE: TRUE
SCALE:
  - NAME_DESC: Dell Inc. DELL P2715Q
    SCALE: 1.5 # 1.31967211
  - NAME_DESC: eDP-1
    SCALE: 1 #SCALE: 1.17213118
MODE:
    - NAME_DESC: Dell Inc. DELL P2715Q
      WIDTH: 3840
      HEIGHT: 2160
      HZ: 60
    - NAME_DESC: eDP-1
      WIDTH: 1920
      HEIGHT: 1080
      HZ: 60
LOG_THRESHOLD: INFO
