ARRANGE: ROW
ALIGN: TOP
ORDER:
  - eDP-1
  - Dell Inc. DELL P2715Q
AUTO_SCALE: TRUE
SCALE:
  - NAME_DESC: Dell Inc. DELL P2715Q
    SCALE: 1.5 # 1.31967211
  - NAME_DESC: eDP-1
    SCALE: 1 #SCALE: 1.17213118
LOG_THRESHOLD: INFO
