# This file has been generated by node2nix 1.2.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "babel-runtime-6.26.0" = {
      name = "babel-runtime";
      packageName = "babel-runtime";
      version = "6.26.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/babel-runtime/-/babel-runtime-6.26.0.tgz";
        sha1 = "965c7058668e82b55d7bfe04ff2337bc8b5647fe";
      };
    };
    "chalk-2.1.0" = {
      name = "chalk";
      packageName = "chalk";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-2.1.0.tgz";
        sha1 = "ac5becf14fa21b99c6c92ca7a7d7cfd5b17e743e";
      };
    };
    "cross-spawn-5.1.0" = {
      name = "cross-spawn";
      packageName = "cross-spawn";
      version = "5.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cross-spawn/-/cross-spawn-5.1.0.tgz";
        sha1 = "e8bd0efee58fcff6f8f94510a0a554bbfa235449";
      };
    };
    "fs-extra-4.0.1" = {
      name = "fs-extra";
      packageName = "fs-extra";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs-extra/-/fs-extra-4.0.1.tgz";
        sha1 = "7fc0c6c8957f983f57f306a24e5b9ddd8d0dd880";
      };
    };
    "minimist-1.2.0" = {
      name = "minimist";
      packageName = "minimist";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-1.2.0.tgz";
        sha1 = "a35008b20f41383eec1fb914f4cd5df79a264284";
      };
    };
    "path-exists-3.0.0" = {
      name = "path-exists";
      packageName = "path-exists";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-exists/-/path-exists-3.0.0.tgz";
        sha1 = "ce0ebeaa5f78cb18925ea7d810d7b59b010fd515";
      };
    };
    "semver-5.4.1" = {
      name = "semver";
      packageName = "semver";
      version = "5.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-5.4.1.tgz";
        sha1 = "e059c09d8571f0540823733433505d3a2f00b18e";
      };
    };
    "source-map-support-0.4.16" = {
      name = "source-map-support";
      packageName = "source-map-support";
      version = "0.4.16";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map-support/-/source-map-support-0.4.16.tgz";
        sha1 = "16fecf98212467d017d586a2af68d628b9421cd8";
      };
    };
    "core-js-2.5.0" = {
      name = "core-js";
      packageName = "core-js";
      version = "2.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-js/-/core-js-2.5.0.tgz";
        sha1 = "569c050918be6486b3837552028ae0466b717086";
      };
    };
    "regenerator-runtime-0.11.0" = {
      name = "regenerator-runtime";
      packageName = "regenerator-runtime";
      version = "0.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/regenerator-runtime/-/regenerator-runtime-0.11.0.tgz";
        sha1 = "7e54fe5b5ccd5d6624ea6255c3473be090b802e1";
      };
    };
    "ansi-styles-3.2.0" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "3.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-3.2.0.tgz";
        sha1 = "c159b8d5be0f9e5a6f346dab94f16ce022161b88";
      };
    };
    "escape-string-regexp-1.0.5" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz";
        sha1 = "1b61c0562190a8dff6ae3bb2cf0200ca130b86d4";
      };
    };
    "supports-color-4.2.1" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "4.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-4.2.1.tgz";
        sha1 = "65a4bb2631e90e02420dba5554c375a4754bb836";
      };
    };
    "color-convert-1.9.0" = {
      name = "color-convert";
      packageName = "color-convert";
      version = "1.9.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-convert/-/color-convert-1.9.0.tgz";
        sha1 = "1accf97dd739b983bf994d56fec8f95853641b7a";
      };
    };
    "color-name-1.1.3" = {
      name = "color-name";
      packageName = "color-name";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-name/-/color-name-1.1.3.tgz";
        sha1 = "a7d0558bd89c42f795dd42328f740831ca53bc25";
      };
    };
    "has-flag-2.0.0" = {
      name = "has-flag";
      packageName = "has-flag";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-flag/-/has-flag-2.0.0.tgz";
        sha1 = "e8207af1cc7b30d446cc70b734b5e8be18f88d51";
      };
    };
    "lru-cache-4.1.1" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-4.1.1.tgz";
        sha1 = "622e32e82488b49279114a4f9ecf45e7cd6bba55";
      };
    };
    "shebang-command-1.2.0" = {
      name = "shebang-command";
      packageName = "shebang-command";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/shebang-command/-/shebang-command-1.2.0.tgz";
        sha1 = "44aac65b695b03398968c39f363fee5deafdf1ea";
      };
    };
    "which-1.3.0" = {
      name = "which";
      packageName = "which";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/which/-/which-1.3.0.tgz";
        sha1 = "ff04bdfc010ee547d780bec38e1ac1c2777d253a";
      };
    };
    "pseudomap-1.0.2" = {
      name = "pseudomap";
      packageName = "pseudomap";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/pseudomap/-/pseudomap-1.0.2.tgz";
        sha1 = "f052a28da70e618917ef0a8ac34c1ae5a68286b3";
      };
    };
    "yallist-2.1.2" = {
      name = "yallist";
      packageName = "yallist";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/yallist/-/yallist-2.1.2.tgz";
        sha1 = "1c11f9218f076089a47dd512f93c6699a6a81d52";
      };
    };
    "shebang-regex-1.0.0" = {
      name = "shebang-regex";
      packageName = "shebang-regex";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/shebang-regex/-/shebang-regex-1.0.0.tgz";
        sha1 = "da42f49740c0b42db2ca9728571cb190c98efea3";
      };
    };
    "isexe-2.0.0" = {
      name = "isexe";
      packageName = "isexe";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isexe/-/isexe-2.0.0.tgz";
        sha1 = "e8fbf374dc556ff8947a10dcb0572d633f2cfa10";
      };
    };
    "graceful-fs-4.1.11" = {
      name = "graceful-fs";
      packageName = "graceful-fs";
      version = "4.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.1.11.tgz";
        sha1 = "0e8bdfe4d1ddb8854d64e04ea7c00e2a026e5658";
      };
    };
    "jsonfile-3.0.1" = {
      name = "jsonfile";
      packageName = "jsonfile";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonfile/-/jsonfile-3.0.1.tgz";
        sha1 = "a5ecc6f65f53f662c4415c7675a0331d0992ec66";
      };
    };
    "universalify-0.1.1" = {
      name = "universalify";
      packageName = "universalify";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/universalify/-/universalify-0.1.1.tgz";
        sha1 = "fa71badd4437af4c148841e3b3b165f9e9e590b7";
      };
    };
    "source-map-0.5.7" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.5.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.5.7.tgz";
        sha1 = "8a039d2d1021d22d1ea14c80d8ea468ba2ef3fcc";
      };
    };
  };
in
{
  create-react-native-app = nodeEnv.buildNodePackage {
    name = "create-react-native-app";
    packageName = "create-react-native-app";
    version = "1.0.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/create-react-native-app/-/create-react-native-app-1.0.0.tgz";
      sha1 = "fc6046f4407bde2727ce0c4eb1354bb1a8c0f9e6";
    };
    dependencies = [
      sources."babel-runtime-6.26.0"
      sources."chalk-2.1.0"
      sources."cross-spawn-5.1.0"
      sources."fs-extra-4.0.1"
      sources."minimist-1.2.0"
      sources."path-exists-3.0.0"
      sources."semver-5.4.1"
      sources."source-map-support-0.4.16"
      sources."core-js-2.5.0"
      sources."regenerator-runtime-0.11.0"
      sources."ansi-styles-3.2.0"
      sources."escape-string-regexp-1.0.5"
      sources."supports-color-4.2.1"
      sources."color-convert-1.9.0"
      sources."color-name-1.1.3"
      sources."has-flag-2.0.0"
      sources."lru-cache-4.1.1"
      sources."shebang-command-1.2.0"
      sources."which-1.3.0"
      sources."pseudomap-1.0.2"
      sources."yallist-2.1.2"
      sources."shebang-regex-1.0.0"
      sources."isexe-2.0.0"
      sources."graceful-fs-4.1.11"
      sources."jsonfile-3.0.1"
      sources."universalify-0.1.1"
      sources."source-map-0.5.7"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Create React Native apps with no build configuration.";
      homepage = https://github.com/react-community/create-react-native-app;
      license = "BSD-3-Clause";
    };
    production = true;
  };
}